# CXXFLAGS+=-O2 -ggdb -DDEBUG
# CXXFLAGS+=-Wall -Wextra

# all: sudoku_solve, ./Test_sample_production

Test_sample_production: Test_sample_production.cpp
	g++ -O3 -o $@ $^ 

clean :
	rm Test_sample_production